### ISSUE TITLE
PGMs for spherical cow / SL2S Paper V model

### ISSUE THREAD

**Issue by drphilmarshall** [astrosonnen/allZeLenses#12]
We'll need two to describe what we are trying to do via importance sampling: the main PGM, and then just the individual lens PGM (without a plate!). This might help us iron out some bugs in the probability theory. Let's start a notebook like [this one](https://github.com/astrosonnen/allZeLenses/blob/master/notebooks/Simple_Mstar_Mh.ipynb) and copy and adapt the PGM code in a corresponding `.py` file.

**Comment by drphilmarshall** [comment]
Ale, it was great to see you this week! I think the whiteboard photos on your phone should set you up for a very nice notebook on the "Fiducial Model" (previously known as the "Spherical Cow" or "Paper V" model ;-) ). Feel free to assign this issue back to me when the PGM and math is typed up, I'm happy to proof-read it for errors etc. Feels like we are on the right track! Safe travels my friend.

**Comment by astrosonnen** [comment]
PGMs are [up](https://github.com/astrosonnen/allZeLenses/blob/master/notebooks/problem_formulation.ipynb)!

**Comment by drphilmarshall** [comment]
Sweet!
