### ISSUE TITLE
Experiments Registry

### ISSUE THREAD

**Issue by drphilmarshall** [astrosonnen/allZeLenses#13]
It'd be good to make a simple markdown file listing the experiments we have tried, and the failure modes they have identified. Preferably with hyperlinks to notebooks containing PGMs and plots, or at least plots.

**Comment by astrosonnen** [comment]
done [here](https://github.com/astrosonnen/allZeLenses/blob/master/notebooks/Failed_Experiments.ipynb)

**Comment by drphilmarshall** [comment]
Good! You might want to insert/display some of your plots, to illustrate
the problems you flushed out. This is actually quite a serious page: a
research notebook listing negative results is a valuable thing.
